services:
  # KowAI Backend Application
  kowai-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://kowai_user:kowai_password@mariadb:3306/kowai
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - LOG_LEVEL=INFO
      - COMPRESSION_ENABLED=true
      - COMPRESSION_LEVEL=7
      # Add your API keys here or use .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT:-https://cloud.appwrite.io/v1}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID:-}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY:-}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      # Mount for development (remove for production)
      - ./app:/app/app:ro
    networks:
      - kowai-network
    restart: unless-stopped

  # MariaDB Database
  mariadb:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=kowai
      - MYSQL_USER=kowai_user
      - MYSQL_PASSWORD=kowai_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "3306:3306"
    networks:
      - kowai-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis for Caching
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - kowai-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # Prefect Server (for AI workflows)
  prefect:
    image: prefecthq/prefect:2-python3.12
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    environment:
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
    volumes:
      - prefect_data:/root/.prefect
    networks:
      - kowai-network
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  prefect_data:
    driver: local

networks:
  kowai-network:
    driver: bridge
