apiVersion: apps/v1
kind: Deployment
metadata:
  name: kowai-backend
  namespace: kowai
  labels:
    app.kubernetes.io/name: kowai-backend
    app.kubernetes.io/component: api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kowai-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kowai-backend
        app.kubernetes.io/component: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: kowai-backend
        image: kowai/backend:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: kowai-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: kowai-config
              key: REDIS_URL
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: kowai-config
              key: DEBUG
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: kowai-config
              key: LOG_LEVEL
        - name: COMPRESSION_ENABLED
          valueFrom:
            configMapKeyRef:
              name: kowai-config
              key: COMPRESSION_ENABLED
        - name: COMPRESSION_LEVEL
          valueFrom:
            configMapKeyRef:
              name: kowai-config
              key: COMPRESSION_LEVEL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: kowai-secrets
              key: SECRET_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: kowai-secrets
              key: OPENAI_API_KEY
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: kowai-secrets
              key: ANTHROPIC_API_KEY
        - name: APPWRITE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: kowai-secrets
              key: APPWRITE_ENDPOINT
        - name: APPWRITE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: kowai-secrets
              key: APPWRITE_PROJECT_ID
        - name: APPWRITE_API_KEY
          valueFrom:
            secretKeyRef:
              name: kowai-secrets
              key: APPWRITE_API_KEY
        - name: PREFECT_API_URL
          valueFrom:
            configMapKeyRef:
              name: kowai-config
              key: PREFECT_API_URL
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      securityContext:
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - kowai-backend
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: kowai-backend-service
  namespace: kowai
  labels:
    app.kubernetes.io/name: kowai-backend
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: kowai-backend
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kowai-backend-hpa
  namespace: kowai
  labels:
    app.kubernetes.io/name: kowai-backend
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kowai-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80